### ISSUE TITLE
kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $

### ISSUE THREAD

**Issue by danny-su** [FalsePattern/ZigBrains#100]
kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $
JSON input: 
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:598)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:596)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:233)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json$default(AbstractJsonLexer.kt:228)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:225)
	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:77)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:102)
	at com.falsepattern.zigbrains.project.toolchain.ZigToolchainEnvironmentSerializable$$serializer.deserialize(ZigToolchainEnvironmentSerializable.kt:31)
	at com.falsepattern.zigbrains.project.toolchain.ZigToolchainEnvironmentSerializable$$serializer.deserialize(ZigToolchainEnvironmentSerializable.kt:31)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
	at com.falsepattern.zigbrains.project.toolchain.tools.ZigCompilerTool.getEnv(ZigCompilerTool.kt:47)
	at com.falsepattern.zigbrains.project.toolchain.tools.ZigCompilerTool$getEnv$1.invokeSuspend(ZigCompilerTool.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:111)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$BuildersKt__BuildersKt(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:52)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.falsepattern.zigbrains.project.toolchain.stdlib.ZigSyntheticLibraryKt.getRoots(ZigSyntheticLibrary.kt:103)
	at com.falsepattern.zigbrains.project.toolchain.stdlib.ZigSyntheticLibraryKt.access$getRoots(ZigSyntheticLibrary.kt:1)
	at com.falsepattern.zigbrains.project.toolchain.stdlib.ZigSyntheticLibrary.roots_delegate$lambda$0(ZigSyntheticLibrary.kt:40)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.falsepattern.zigbrains.project.toolchain.stdlib.ZigSyntheticLibrary.getRoots(ZigSyntheticLibrary.kt:39)
	at com.falsepattern.zigbrains.project.toolchain.stdlib.ZigSyntheticLibrary.getSourceRoots(ZigSyntheticLibrary.kt:67)
	at com.intellij.workspaceModel.core.fileIndex.impl.NonIncrementalContributors.computeFileSets(NonIncrementalContributors.kt:161)
	at com.intellij.workspaceModel.core.fileIndex.impl.NonIncrementalContributors.updateIfNeeded(NonIncrementalContributors.kt:51)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:158)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:98)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:267)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.isUnderIgnored(ProjectFileIndexImpl.java:78)
	at com.intellij.openapi.roots.impl.ProjectFileIndexFacade.isUnderIgnored(ProjectFileIndexFacade.java:73)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.isExcludedOrIgnored(FileManagerImpl.java:443)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectoryImpl(FileManagerImpl.java:429)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectory(FileManagerImpl.java:422)
	at com.intellij.psi.impl.PsiManagerImpl.findDirectory(PsiManagerImpl.java:175)
	at com.intellij.psi.AbstractFileViewProvider.shouldCreatePsi(AbstractFileViewProvider.java:89)
	at com.intellij.psi.SingleRootFileViewProvider.createFile(SingleRootFileViewProvider.java:146)
	at com.intellij.psi.SingleRootFileViewProvider.getPsiInner(SingleRootFileViewProvider.java:102)
	at com.intellij.psi.AbstractFileViewProvider.getPsi(AbstractFileViewProvider.java:185)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:384)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:163)
	at com.intellij.psi.util.PsiUtilCore.findFileSystemItem(PsiUtilCore.java:518)
	at com.intellij.ide.PsiBasedFileIconProvider.getIcon(PsiBasedFileIconProvider.java:18)
	at com.intellij.ide.FileIconUtil.getIconFromProviders(FileIconUtil.kt:23)
	at com.intellij.util.IconUtilKt.computeFileIconImpl(IconUtil.kt:559)
	at com.intellij.openapi.fileEditor.impl.EditorsSplittersKt$computeFileEntry$tabIconTask$1.invokeSuspend$lambda$0(EditorsSplitters.kt:1107)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:114)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable$lambda$4(InternalReadAction.kt:104)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2$lambda$1(cancellableReadAction.kt:32)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:351)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:972)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2(cancellableReadAction.kt:30)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:28)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:103)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:87)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:74)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invokeSuspend(InternalReadAction.kt:53)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:49)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:62)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:29)
	at com.intellij.openapi.fileEditor.impl.EditorsSplittersKt$computeFileEntry$tabIconTask$1.invokeSuspend(EditorsSplitters.kt:1106)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)

**Comment by mkulak** [comment]
I got the same exception when opening Zig project after I've upgraded to Zig `0.14.0`. 
I use ZigBrains `20.3.0-243`

**Comment by FalsePattern** [comment]
Should be fixed in 21.0.0

**Comment by mkulak** [comment]
I've updated to `21.1.0-243`. Exception on project open is gone. Now I can open and run Zig files. But completion and code navigation doesn't work - i.e. it always say "no suggestions" and "cannot find declaration to go", even for local functions defined in the same file. In settings "Languages & Frameworks" - "Zig" -"Toolchain version" is "failed to run zig env". 
<img width="715" alt="Image" src="https://github.com/user-attachments/assets/9479da3a-f7c3-40f3-b102-f82910a46818" />
(not sure if we need separate issue for it)

I use:
`IntelliJ IDEA 2024.3.4.1 (Ultimate Edition) Build #IU-243.25659.59, built on March 5, 2025` 

```
[20:17:13] ▶ zls version
0.14.0
[20:17:21] ▶ zls env
{
 "version": "0.14.0",
 "global_cache_dir": "/Users/user/Library/Caches/zls",
 "global_config_dir": "/Library/Preferences",
 "local_config_dir": "/Users/user/Library/Application Support",
 "config_file": null,
 "log_file": "/Users/user/Library/Caches/zls/zls.log"
}
[20:17:25] ▶ zig version
0.14.0
error: Zig was built/linked incorrectly: LLVM and Clang have separate copies of libc++
       If you are dynamically linking LLVM, make sure you dynamically link libc++ too
```

**Comment by FalsePattern** [comment]
I need to verify something, is `/usr/local/bin/zig` a symlink?

**Comment by FalsePattern** [comment]
> error: Zig was built/linked incorrectly: LLVM and Clang have separate copies of libc++
> If you are dynamically linking LLVM, make sure you dynamically link libc++ too

This seems to be the problem, your zig binary is throwing an error for some reason. If the zig executable returns a non-zero error code, zigbrains assumes that it's broken.

**Comment by FalsePattern** [comment]
I've added more descriptive errors in 22.0.0

**Comment by mkulak** [comment]
This error that `zig version` returns is due to [this homebrew formula issue](https://github.com/Homebrew/homebrew-core/issues/210073)
I've reinstall zig 0.14.0 manually, checked that it's no longer returns the error.
Updated ZigBrains plugin to 0.22.0 (new diagnostic really helped!)
Now certain functionality is restored (i can navigate to local function declarations).
But still no inlay hints, no non-local "jump to declaration" and no "show expression type" (all of these used to work in 0.13.0).
I've got new exception in IDEA (not sure when exactly, shortly after I restarted and reopened the project)
```
Unhandled exception in [ComponentManager(ApplicationImpl@1340526683), com.intellij.codeWithMe.ClientIdContextElementPrecursor@40683f41, CoroutineName(com.falsepattern.zigbrains.shared.ZigAppService), Dispatchers.Default]

java.lang.IllegalStateException: Cannot find an entity by id LibraryEntity-:-2
	at com.intellij.platform.workspace.storage.impl.AbstractEntityStorage.entityDataByIdOrDie$intellij_platform_workspace_storage(ImmutableEntityStorageImpl.kt:985)
	at com.intellij.platform.workspace.storage.impl.WorkspaceBuilderChangeLogKt.getOriginalEntityData(WorkspaceBuilderChangeLog.kt:552)
	at com.intellij.platform.workspace.storage.impl.MutableEntityStorageImpl.modifyEntity(ImmutableEntityStorageImpl.kt:296)
	at com.intellij.platform.workspace.jps.entities.DependenciesKt.modifyLibraryEntity(dependencies.kt:74)
	at com.falsepattern.zigbrains.project.toolchain.stdlib.ZigSyntheticLibrary$Companion.reload$lambda$2(ZigSyntheticLibrary.kt:101)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl.updateProjectModel(WorkspaceModelImpl.kt:164)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl.update$lambda$12(WorkspaceModelImpl.kt:212)
	at com.intellij.openapi.application.CoroutinesKt$writeAction$2.invokeSuspend$lambda$1$lambda$0(coroutines.kt:243)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction$lambda$6(AnyThreadWriteThreadingSupport.kt:381)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction(AnyThreadWriteThreadingSupport.kt:389)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction(AnyThreadWriteThreadingSupport.kt:381)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:902)
	at com.intellij.openapi.application.CoroutinesKt$writeAction$2.invokeSuspend$lambda$1(coroutines.kt:243)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:341)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:233)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:232)
	at com.intellij.openapi.application.CoroutinesKt$writeAction$2.invokeSuspend(coroutines.kt:242)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:44)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:236)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:25)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:117)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:573)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:917)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1045)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1054)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1054)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ApplicationImpl@1340526683), com.intellij.codeWithMe.ClientIdContextElementPrecursor@40683f41, CoroutineName(com.falsepattern.zigbrains.shared.ZigAppService), StandaloneCoroutine{Cancelled}@70fcef0a, Dispatchers.Default]
```

**Comment by FalsePattern** [comment]
Should be fixed in 22.0.1

**Comment by mkulak** [comment]
No exceptions in `22.0.1`, looks very stable.  "Show type" still doesn't work though but I guess it should be a different issue.
Looks like we can close this one.

Kudos for fixing it so quickly
